### ISSUE TITLE
`createApi` errors when TypeScript `dom` `lib` is not included

### ISSUE THREAD

**Issue by cabello** [unsplash/unsplash-js#166] opened 2021-03-16 20:34 UTC
Hello 👋 

I am integrating with unsplash for a project. While I was successful I found the following problem:

#### Steps to Reproduce

Use `createApi` in Typescript projects.

#### Observed Behaviour

<img width="1329" alt="Screen Shot 2021-03-16 at 4 29 45 PM" src="https://user-images.githubusercontent.com/60936/111375752-05b55e80-8675-11eb-85c8-8618dde33f25.png">

In order to use Typescript I ended up doing:

```typescript
// @ts-ignore
const unsplash = createApi({
  accessKey: functions.config().unsplash.access_key,
  fetch,
});
```

#### Expected Behaviour

`createApi` code should be valid with Typescript codebase if following documentation instructions.

#### Technical Notes

```
"unsplash-js": "^7.0.4"
"typescript": "^3.8.0"
```

I also tried with typescript v4, yielding same result.

Thank you, let me know if I can provide more info.

**Comment by OliverJAsh** [comment] 2021-03-16 21:06
Unfortunately I am able to reproduce:

![image](https://user-images.githubusercontent.com/921609/111379785-6d7ea000-869b-11eb-8f4f-a2370c8ee8f6.png)

Can you send a reduced test case in the form of a repository I can clone and test for myself?

**Comment by cabello** [comment] 2021-03-16 21:35
Hi @OliverJAsh , thank you for the quick reply, here it goes: https://github.com/cabello/unsplash-demo/tree/main

**Comment by OliverJAsh** [comment] 2021-03-16 22:12
Thanks! It looks like the issue happens when using the TS compiler option `lib` and `dom` is not listed. This means that globals such as `fetch` and `RequestInit` are missing.

If adding `dom` to `lib` is not an option, you can fix the issue by adding types for `fetch` and `RequestInit` to the global scope:

```ts
import * as nodeFetch from 'node-fetch';
import { createApi } from 'unsplash-js';

declare global {
    var fetch: typeof nodeFetch.default;
    type RequestInit = nodeFetch.RequestInit & {
        cache?: unknown;
        credentials?: unknown;
        integrity?: unknown;
        keepalive?: unknown;
        mode?: unknown;
        referrer?: unknown;
        referrerPolicy?: unknown;
        window?: unknown;
    };
}

const unsplash = createApi({
    accessKey: 'some access key',
});

export default unsplash;
```

It's a bit ugly, ideally you could just do this:

```ts
declare global {
    var fetch: typeof nodeFetch.default;
    type RequestInit = nodeFetch.RequestInit;
}
```

I'll see if we can make that possible.

**Comment by OliverJAsh** [comment] 2021-03-16 22:16
Btw the problem would have been more obvious if you weren't using `skipLibCheck`, e.g.

```
node_modules/unsplash-js/dist/helpers/request.d.ts:12:46 - error TS2304: Cannot find name 'RequestInit'.

12 declare type AdditionalPerFetchParams = Omit<RequestInit, keyof FetchParams>;
                                                ~~~~~~~~~~~

node_modules/unsplash-js/dist/helpers/request.d.ts:25:20 - error TS2304: Cannot find name 'fetch'.

25     fetch?: typeof fetch;
                      ~~~~~
```

I would recommend disabling that compiler option.

**Comment by OliverJAsh** [comment] 2021-03-16 22:33
I just pushed a fix. With v7.0.6 you should be able to do this:

```ts
import * as nodeFetch from 'node-fetch';
import { createApi } from 'unsplash-js';

declare global {
    var fetch: typeof nodeFetch.default;
    type RequestInit = nodeFetch.RequestInit;
    type Response = nodeFetch.Response;
}

const unsplash = createApi({
    accessKey: 'some access key',
});

export default unsplash;
```

This is only necessary if you're not using the `dom` `lib`.

**Closed by OliverJAsh** 2021-03-16 22:33 UTC

**Comment by cabello** [comment] 2021-03-16 22:48
Oh yeah 😅 I forgot to mention I added `skipLibCheck` when I integrated with unsplash-js. I did try defining the `Request` in some `global.d.ts` but I missed a few things I am sure, thanks for spotting that. 🙇

**Comment by cabello** [comment] 2021-03-16 23:03
Hi @OliverJAsh if I try the code as suggested and having removed `skipLibChecks` this what I get now:

They all seem to be the same error: `"cache"' is not assignable to type`.

```
> tsc

node_modules/unsplash-js/dist/methods/collections/index.d.ts:6:119 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

6     handleRequest: (a: CollectionId & PaginationParams & OrientationParam, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/collections/index.d.ts:13:81 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

13     handleRequest: (a: CollectionId, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/collections/index.d.ts:17:123 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

17     handleRequest: (a: Pick<PaginationParams, "page" | "perPage"> | undefined, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/collections/index.d.ts:24:81 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

24     handleRequest: (a: CollectionId, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/photos/index.d.ts:7:97 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

7     handleRequest: (a: PaginationParams | undefined, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/photos/index.d.ts:14:76 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

14     handleRequest: (a: PhotoId, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/photos/index.d.ts:18:76 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

18     handleRequest: (a: PhotoId, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/photos/index.d.ts:28:83 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

28     } & OrientationParam) | undefined, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/photos/index.d.ts:34:51 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

34     }, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/search/index.d.ts:24:87 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

24     handleRequest: (a: SearchPhotosParams, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/search/index.d.ts:28:81 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

28     handleRequest: (a: SearchParams, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/search/index.d.ts:32:81 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

32     handleRequest: (a: SearchParams, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/users/index.d.ts:9:77 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

9     handleRequest: (a: UserName, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/users/index.d.ts:15:100 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

15     } & OrientationParam & UserName & PaginationParams, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/users/index.d.ts:22:115 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

22     handleRequest: (a: OrientationParam & UserName & PaginationParams, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/unsplash-js/dist/methods/users/index.d.ts:29:96 - error TS2344: Type '"headers" | "body" | "redirect" | "signal" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "referrer" | "referrerPolicy" | "window"' does not satisfy the constraint '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.
  Type '"cache"' is not assignable to type '"timeout" | "headers" | "method" | "body" | "redirect" | "signal" | "agent" | "compress" | "follow" | "size"'.

29     handleRequest: (a: UserName & PaginationParams, additionalFetchOptions?: Pick<RequestInit, "headers" | "body" | "cache" | "credentials" | "integrity" | "keepalive" | "mode" | "redirect" | "referrer" | "referrerPolicy" | "signal" | "window"> | undefined) => import("../../helpers/request").CompleteRequestParams;
                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by OliverJAsh** [comment] 2021-03-17 09:25
@cabello I just pushed another fix. Can you try 7.0.7?

**Comment by cabello** [comment] 2021-03-17 19:00
@OliverJAsh I celebrated too early:

```typescript
import * as nodeFetch from 'node-fetch';
import { createApi } from 'unsplash-js';

declare global {
  var fetch: typeof nodeFetch.default;
  type RequestInit = nodeFetch.RequestInit;
  type Response = nodeFetch.Response;
}

const unsplash = createApi({
  accessKey: 'some-string',
  fetch: nodeFetch,
});
```

Results in, on the `fetch: nodeFetch` line:

```
(property) fetch: typeof nodeFetch
Property 'isRedirect' is missing in type 'typeof import("/Users/danilo/project/node_modules/@types/node-fetch/index")' but required in type 'typeof fetch'.ts(2741)
index.d.ts(219, 14): 'isRedirect' is declared here.
request.d.ts(26, 5): The expected type comes from property 'fetch' which is declared here on type 'InitParams'
```

Thoughts?

**Comment by OliverJAsh** [comment] 2021-03-17 19:09
Ah my bad, try this:

```diff
-    fetch: nodeFetch,
+    fetch: nodeFetch.default,
```

**Comment by cabello** [comment] 2021-03-17 19:10
As an experiment I also added `DOM` to my compiler options and removed the type declarations and resulted in similar issues as well.

```typescript
import * as nodeFetch from 'node-fetch';
import { createApi } from 'unsplash-js';

const unsplash = createApi({
  accessKey: functions.config().unsplash.access_key,
  fetch: nodeFetch.default,
});
```

Resulted in:

```typescript
(property) fetch: typeof nodeFetch.fetch
Type 'typeof fetch' is not assignable to type '(input: RequestInfo, init?: RequestInit | undefined) => Promise<Response>'.
  Types of parameters 'url' and 'input' are incompatible.
    Type 'RequestInfo' is not assignable to type 'import("/Users/danilo/project/node_modules/@types/node-fetch/index").RequestInfo'.
      Type 'Request' is not assignable to type 'RequestInfo'.
        Type 'Request' is missing the following properties from type 'Request': context, compress, counter, follow, and 6 more.ts(2322)
request.d.ts(26, 5): The expected type comes from property 'fetch' which is declared here on type 'InitParams'
```

And if I tried as suggested in the docs:

```typescript
import nodeFetch from 'node-fetch';
import { createApi } from 'unsplash-js';

const unsplash = createApi({
  accessKey: functions.config().unsplash.access_key,
  fetch: nodeFetch,
});
```

Same errors:

```typescript
(property) fetch: typeof nodeFetch
Type 'typeof fetch' is not assignable to type '(input: RequestInfo, init?: RequestInit | undefined) => Promise<Response>'.
  Types of parameters 'url' and 'input' are incompatible.
    Type 'RequestInfo' is not assignable to type 'import("/Users/danilo/workspace/private/venue-client/node_modules/@types/node-fetch/index").RequestInfo'.
      Type 'Request' is not assignable to type 'RequestInfo'.
        Type 'Request' is missing the following properties from type 'Request': context, compress, counter, follow, and 6 more.ts(2322)
request.d.ts(26, 5): The expected type comes from property 'fetch' which is declared here on type 'InitParams'
```

**Comment by cabello** [comment] 2021-03-17 19:12
> Ah my bad, try this:
> 
> ```diff
> -    fetch: nodeFetch,
> +    fetch: nodeFetch.default,
> ```

I think this change without the DOM in compiler options plus the type declarations as suggested worked, let me test in production :)

**Comment by OliverJAsh** [comment] 2021-03-17 19:12
`node-fetch` isn't compatible with the `fetch` types defined in the `DOM` lib. You have to choose between using the `DOM` lib (in which case you don't need `node-fetch`) or using `node-fetch` and no `DOM` lib.

**Comment by cabello** [comment] 2021-03-17 19:16
I see, sorry! My knowledge in backend node.js is limited, I appreciate the back & forth and you helping me with the solution 🙏 .

**Comment by OliverJAsh** [comment] 2021-03-17 19:24
No problem, I'm glad we got it working. Thank you for your help finding the issue!

**Comment by jspantheonlab** [comment] 2021-09-20 07:19
i found a solution that using [cross-fetch](https://www.npmjs.com/package/cross-fetch), will solve the typings issue for fetch type from `createApi` interface.
```
import nodeFetch from 'cross-fetch';
```

**Comment by swalker326** [comment] 2021-10-08 16:08
> i found a solution that using [cross-fetch](https://www.npmjs.com/package/cross-fetch), will solve the typings issue for fetch type from `createApi` interface.
> 
> ```
> import nodeFetch from 'cross-fetch';
> ```

THANK YOU
